package org.pvemu.jelly.database;

import java.sql.ResultSet;

/**
 * Data Active Object
 * @author Vincent Quatrevieux <quatrevieux.vincent@gmail.com>
 * @param <T> the model generated by this DAO
 */
public abstract class DAO<T extends Model> {

    /**
     * The table name
     * @return table name
     */
    protected abstract String tableName();

    /**
     * The column name of the primary key
     * @return the primary key name
     */
    protected String primaryKey() {
        return "id";
    }
    
    /**
     * Create a model by a ResultSet object
     * @param RS the result of a query
     * @return The model
     */
    abstract protected T createByResultSet(ResultSet RS);
}
